// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omkrbduvavbkmbjtphgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ta3JiZHV2YXZia21ianRwaGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTYyMTgsImV4cCI6MjA2NDQzMjIxOH0.FqYKGOp7J5o7Ye0umA5gO0VDOCkZxmYNu6cBLZqXQVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);